# Generated by Django 5.2.4 on 2025-07-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_subtitle', models.CharField(max_length=200)),
                ('section_description', models.TextField()),
                ('journey_title', models.CharField(max_length=200)),
                ('journey_paragraphs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_subtitle', models.CharField(max_length=200)),
                ('section_description', models.TextField()),
                ('cta_title', models.CharField(max_length=200)),
                ('cta_description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('location_note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('initials', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('resume_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_subtitle', models.CharField(max_length=200)),
                ('section_description', models.TextField()),
                ('view_all_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_subtitle', models.CharField(max_length=200)),
                ('section_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Code2', 'Code2'), ('Rocket', 'Rocket'), ('Users', 'Users'), ('Zap', 'Zap')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='api.aboutsection')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('Mail', 'Mail'), ('Phone', 'Phone')], max_length=50)),
                ('contact_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='api.contactsection')),
            ],
        ),
        migrations.CreateModel(
            name='HeroAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(max_length=255)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_actions', to='api.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='api.navigation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('github', models.URLField()),
                ('live', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('tech', models.JSONField(default=list)),
                ('projects_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.projectssection')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('skills_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.skillssection')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('email', 'Email')], max_length=20)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('Github', 'Github'), ('Linkedin', 'Linkedin'), ('Mail', 'Mail')], max_length=50)),
                ('contact_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.contactsection')),
            ],
        ),
    ]
